/*
 * generated by Xtext
 */
package org.xtext.example.umldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlDslUiModule extends org.xtext.example.umldsl.ui.AbstractUmlDslUiModule {
	public UmlDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
