/*
 * generated by Xtext
 */
package org.xtext.example.umldsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UmlDslRuntimeModule extends org.xtext.example.umldsl.AbstractUmlDslRuntimeModule {

}
