grammar org.xtext.example.umldsl.UmlDsl with org.eclipse.xtext.common.Terminals

generate umlDsl "http://www.xtext.org/example/umldsl/UmlDsl"

import "http://www.eclipse.org/uml2/5.0.0/UML" as uml
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
 
 
Model:
    elements+=Element*
;
 
Element:
    "element" name=ID "mapsTo" ref=[uml::Class|FQN]
;
 
FQN returns ecore::EString:
    ID ("." ID)*
;
